CONDA_BUILD_SYSROOT:           # [osx]
  - /opt/MacOSX10.9.sdk        # [osx]

macos_min_version:             # [osx]
  - 10.9                       # [osx]

macos_machine:                 # [osx]
  - x86_64-apple-darwin13.4.0  # [osx]

MACOSX_DEPLOYMENT_TARGET:      # [osx]
  - 10.9                       # [osx]

libpng:
  - 1.6.37 h2573ce8_0 # [osx]
  - 1.6.37 hed695b0_0 # [linux]
