{% set name = "icecream" %}
{% set version = "10b9468f5bd30a0fdb058901e91e7a29f1bfbd42" %}
{% set friendly_version = "1.3" %}
{% set sha256 = "259e9ca80fcc993f90a7b0153a52f2ec417a0cf0b6a15c014460f4646938cdd8" %}

package:
  name: {{ name }}
  version: {{ friendly_version }}

source:
  - url: https://github.com/icecc/{{ name }}/archive/{{ version }}.tar.gz
    fn: {{ name }}-{{ version }}.tar.gz
    sha256: {{ sha256 }}
    folder: icecream

  - url: http://mooseframework.inl.gov/source_packages/lzo-2.09.tar.gz
    sha256: f294a7ced313063c057c504257f437c8335c41bfeed23531ee4e6a2b87bcb34c
    folder: lzo

  - url: http://mooseframework.inl.gov/source_packages/zstd-1.4.3.tar.gz
    sha256: e88ec8d420ff228610b77fba4fbf22b9f8b9d3f223a40ef59c9c075fcdad5767
    folder: zstd

  - url: http://mooseframework.inl.gov/source_packages/libarchive-3.4.0.tar.gz
    sha256: 8643d50ed40c759f5412a3af4e353cffbce4fdf3b5cf321cb72cacf06b2d825e
    folder: libarchive

  - url: http://mooseframework.inl.gov/source_packages/libcap-ng-0.7.8.tar.gz
    sha256: c21af997445cd4107a55d386f955c5ea6f6e96ead693e9151277c0ab5f97d05f
    folder: libcap

build:
  number: 2  # [linux,osx]
  skip: true # [win]

requirements:
  build:
    - pkg-config
    - autoconf
    - automake
    - libtool
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}

test:
  commands:
    - test -f $PREFIX/icecream/sbin/iceccd
    - test -f $PREFIX/icecream/bin/icecc

about:
  home: https://github.com/icecc/icecream
  license: GNU
  summary: 'Icecream is a centralized distributed parallel scheduler.'

extra:
  recipe-maintainers:
    - milljm
