{% set name = "moose-pylatexenc" %}
{% set version = "2.1" %}
{% set sha256 = "68f6de3921c54d09edb23f2e7625f047d3645cf4f341cc89153e466918411e99" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/bd/6d/148934130b53fdccc7f9b35926e883bbe635f8873c3ddcb5c8503b0d018d/pylatexenc-2.1.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0  # [linux,osx]
  skip: true # [win]
  script: "{{ PYTHON }} setup.py install"

requirements:
  build:
    - setuptools
    - python {{ python }}

  run:
    - python {{ python }}

test:
  imports:
    - pylatexenc

about:
  home: https://pypi.org/project/pylatexenc/
  license: MIT
  summary: 'Simple LaTeX parser providing latex-to-unicode and unicode-to-latex conversion'

extra:
  recipe-maintainers:
    - milljm
