{% set version = "3.11.4" %}
{% set sha256 = "319cb5a875a692a67fe5b1b90009ba8f182e21921ae645d38106544aff20c3c1" %}
{% set petsc_build = 3 %}

package:
  name: moose-petsc
  version: {{ version }}

source:
  fn: petsc-{{ version }}.tar.gz
  url: http://ftp.mcs.anl.gov/pub/petsc/release-snapshots/petsc-{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - ignore-not-invalid.patch
    - no-cppflags-in-pkgconfig-cflags.patch

build:
  skip: true  # [win]
  number: {{ petsc_build }}
  run_exports:
    - {{ pin_subpackage('moose-petsc', max_pin='x.x')}}

requirements:
  build:
    - moose-mpich {{ moose_mpich }}
    - pkg-config

  host:
    - cmake
    - moose-mpich
    - libblas   # [osx]
    - libcblas  # [osx]
    - liblapack # [osx]

  run:
    - moose-mpich {{ moose_mpich }}
    - libblas   # [osx]
    - libcblas  # [osx]
    - liblapack # [osx]

test:
  requires:
    - pkg-config
    - moose-mpich {{ moose_mpich }}

  files:
    - tests/ex1.c
    - tests/ex1f.F90
    - tests/makefile
  commands:
    - pkg-config --validate PETSc
    - pkg-config --cflags PETSc
    - pkg-config --libs PETSc

about:
  home: http://www.mcs.anl.gov/petsc/
  summary: 'PETSc: Portable, Extensible Toolkit for Scientific Computation'
  license: BSD 2-Clause
  license_file: LICENSE
  license_family: BSD

extra:
  recipe-maintainers:
    - milljm
